### ISSUE TITLE
table not fully visible in pdf

### ISSUE THREAD

**Issue by bit** [archipelagosjournal/archipelagos#1]
i.e. here http://smallaxe.net/sxarchipelagos/assets/issue01/haynes-mapping.pdf

**Comment by elotroalex** [comment]
thanks @bit! finally found some decent internet and some time. researching now.

**Comment by elotroalex** [comment]
figured out what the table issue was: the font. the designer had picked a closed font. lesson learned. researching open fonts. in the meantime I wanted to let you know that _all tests are passing_. Good times.

**Comment by elotroalex** [comment]
problem temporarily solved. moving the ConTeXt environment to docker
