### ISSUE TITLE
table broken in issue 1 | haynes | PDF

### ISSUE THREAD

**Issue by elotroalex** [archipelagosjournal/archipelagos#20]
I think it goes way back. I have reverted to many previous states and still find it broken.

**Comment by elotroalex** [comment]
a possible solution to this is if you have a good copy of the PDF generated in your computer. since we won't be regenerating past issues, we could just replace this one on the server

**Comment by elotroalex** [comment]
solved it by going into your docker

**Comment by Denubis** [comment]
What version of context are you running?

**Comment by elotroalex** [comment]
hmm. good question...

mtx-context     | ConTeXt Process Management 0.63
mtx-context     |
mtx-context     | main context file: /Users/elotroalex/context/tex/texmf-context/tex/context/base/mkiv/context.mkiv
mtx-context     | current version: 2016.06.05 16:26

**Comment by Denubis** [comment]
I think we resolved this by telling you to upgrade?
