### ISSUE TITLE
tex error

### ISSUE THREAD

**Issue by elotroalex** [archipelagosjournal/archipelagos#27]
for issue 3

`tex error       > tex error on line 8 in file /Users/elotroalex/context/tex/texmf-context/tex/context/base/mkiv/cont-yes.mkiv: ! I can't find file `./update'.`

**Comment by elotroalex** [comment]
@Denubis  was this fixed? I think so

**Comment by Denubis** [comment]
I think so? Very old issue...

**Comment by elotroalex** [comment]
good morning! 

sweet. closing.

**Comment by elotroalex** [comment]
(I think we're having a good day in the USA)
