### ISSUE TITLE
allow italics in caption for PDFs

### ISSUE THREAD

**Issue by elotroalex** [archipelagosjournal/archipelagos#31]

**Comment by Denubis** [comment]
no. just the title of the paintings
in the Ferrer
sample:

{% include image.html
    img="issue03/ferrer-3.jpg"
    title="Figure 3. Teresita Fernández, *Aponte*, 2017; pyrite, oil, and graphite on wood panel, 21.5 x 36 x 2 in. overall (courtesy of the artist and Lehmann Maupin, New York; photograph by Yolanda Navas)."
    caption="Figure 3. Teresita Fernández, *Aponte*, 2017; pyrite, oil, and graphite on wood panel, 21.5 x 36 x 2 in. overall (courtesy of the artist and Lehmann Maupin, New York; photograph by Yolanda Navas)." %}

**Comment by elotroalex** [comment]
Checking that you can still get notifications in the public repo @Denubis. This is a good one, since I don't think I ever solved it for [the web side of the house.](http://127.0.0.1:4000/es/issue03/ferrer-rodriguez.html) Re-assigning to myself. 

This still shows up as `Figure 3. Teresita Fernández, *Aponte*, 2017; pyrite, oil, and graphite on wood panel...` on my side.

**Comment by Denubis** [comment]
I still get noficiations.

**Comment by elotroalex** [comment]
sweet
