### ISSUE TITLE
quotes inside image include title breaks html generation in Jekyll

### ISSUE THREAD

**Issue by elotroalex** [archipelagosjournal/archipelagos#32]
The issue seems to be that the alt value gets populated with this value, and a quotation mark inside the alt value will close it prematurely. Jekyll seems to pick up on this problem and pre-emptively and uselessly converts the angle brackets into hex values. Here's an example of the generated html:

``` html
&lt;a href="https://archive.org/details/tableaudesfinanc00slsn" title="Figure 1. "Tableau des Finances et du Commerce de la partie Françoise de St. Domingue," 1792 (detail). Copy in the John Carter Brown Library, Brown University." target="_blank"&gt;
    
        &lt;img src="/sxarchipelagos/images/issue03/nesbitt-1.jpg" alt="Figure 1. "Tableau des Finances et du Commerce de la partie Françoise de St. Domingue," 1792 (detail). Copy in the John Carter Brown Library, Brown University."/&gt;
    
    &lt;/a&gt;
```

**Comment by elotroalex** [comment]
In honor of the persistent criminality of quotation marks here's a list of uses of quotation marks. We can transfer the list to a wiki page later, once this issue is out. That wiki page could be documentation on markup standards that work with our system:

- In YAML on the header: Solution is to use block scalars using `>`. The block itself should use spaces not tabs, and begin two spaces from the key indent.
- In the image includes: use `&quot;`
- In titles: Should work out of the box.
- In config.yml: Avoided

**Comment by Denubis** [comment]
{% include image.html
    img="issue03/nesbitt-1.jpg"
    title='Figure 1. &amp;quot;Tableau des Finances et du Commerce de la partie Françoise de St. Domingue,&amp;quot; 1792 (detail). Copy in the John Carter Brown Library, Brown University.'
    caption='Figure 1. &amp;quot;Tableau des Finances et du Commerce de la partie Françoise de St. Domingue,&amp;quot; 1792 (detail). Copy in the John Carter Brown Library, Brown University.'
    url="https://archive.org/details/tableaudesfinanc00slsn" %}

produces:
![Screenshot from 2019-07-04 22-35-50](https://user-images.githubusercontent.com/243503/60667130-1bd4b880-9eac-11e9-9245-eedfd4032097.png)
in pdf

![Screenshot from 2019-07-04 22-36-18](https://user-images.githubusercontent.com/243503/60667160-2b540180-9eac-11e9-8554-a00a5d756be0.png)
in jekyll

Internal quotes in subject matter should therefore be used as &quot;, and should have single quotes as the string demarcation. (Double quotes normally for string demarcation though)

**Comment by elotroalex** [comment]
closing and referencing from production notes elsewhere
