### ISSUE TITLE
missing figure 3 on Goffee PDF

### ISSUE THREAD

**Issue by elotroalex** [archipelagosjournal/archipelagos#45]
And we're live. Ok, now we can relax and find time when we can to look at these tickets instead of rushing to meet a conference deadline. This one is an easy one. I'm taking a look at the markdown to see if I catch the culprit. Brb

[Link to file](http://archipelagosjournal.org/assets/issue05/goffe-unmapping.pdf)

![tao-missing-fig-3](https://user-images.githubusercontent.com/242606/101224461-a949a880-365c-11eb-97c7-cbbbae9b0fee.jpg)

**Comment by Denubis** [comment]
So tasks are: audio and this?

**Comment by Denubis** [comment]
`fig3.jpg` != `fig3.JPG`

**Comment by elotroalex** [comment]
yeah, just found it. fixed and pushed

**Comment by Denubis** [comment]
Just did same

**Comment by elotroalex** [comment]
the audio is no rush. for real. authors are happy with what we have so far. so it's a relax kind of thing. i'll start taking a look at the other issues too, to do them at leisure.

**Comment by Denubis** [comment]
Ok, then that's going to be work for leave. ... Recompiling and committing.

**Comment by elotroalex** [comment]
yup. that's all she wrote for now. round 5 in the bag. not too shabby for a crazy idea we had before the nazis took over.

**Comment by Denubis** [comment]
Resolved in https://github.com/archipelagosjournal/archipelagos/commit/f9994ebc84fed7f1b0ce7368b922617826f3a5da

**Comment by elotroalex** [comment]
sweet. closing.
