### ISSUE TITLE
Generating deletes the previous issue PDF folder

### ISSUE THREAD

**Issue by elotroalex** [archipelagosjournal/archipelagos#54]
When we regened 4-7 it erased 3. Same thing happened when we generated 7, it erased 6

**Comment by Denubis** [comment]
No, this is more because I run makeSingleIssue on the previous, it fails, and I give up. The repo generation is only for the specific folder you request. 

Closing as wontfix.

**Comment by elotroalex** [comment]
Ah! Phew
