### ISSUE TITLE
hyperlink Juliet to a bio on sxa Credits page

### ISSUE THREAD

**Issue by klglover** [archipelagosjournal/archipelagos#6]
text for Ali bio:
Juliet Ali is an artist and graphic designer. She is the art director of the Small Axe Project and has been designing the print journal since 2004. She holds an MFA in Illustration from the Fashion Institute of Technology, New York. Her experience in graphic design spans over thirty years in various industries, including advertising, toys, jewelry, home furnishing, and outdoor media. She taught art for three and a half years for the Board of Education, Trinidad, West Indies, and has been involved in the American Institute of Graphic Arts (AIGA) mentoring program for students from the High School of Art and Design. In 2013 she participated in a group show Dreams Lived/Dreams Shattered: MLK, JFK 50 Years Later held at FIT gallery. Since 2008 she owned and managed her own graphic design/consultancy business Astryd Design Inc.

**Comment by elotroalex** [comment]
done
