### ISSUE TITLE
add Editorial Board members to sxa Credits page

### ISSUE THREAD

**Issue by klglover** [archipelagosjournal/archipelagos#7]
Yarimar Bonilla is Associate Professor of anthropology and Latino & Caribbean Studies at Rutgers University, where she is on the executive board for the Advanced Institute for Critical Caribbean Studies. She teaches and writes about social movements, colonial legacies, and the politics of history in the Atlantic World. She is the author of Non-Sovereign Futures: French Caribbean Politics in the Wake of Disenchantment (2015) and is currently working on a book project about the statehood movement in Puerto Rico.

Vincent Brown, Charles Warren Professor of History and Professor of African and African American Studies, is a multi-media historian with a keen interest in the political implications of cultural practice.  He directs the History Design Studio and teaches courses in Atlantic history, African diaspora studies, and the history of slavery. Brown is the author of The Reaper's Garden: Death and Power in the World of Atlantic Slavery (Harvard University Press, 2008) and producer of an audiovisual documentary about the anthropologist Melville J. Herskovits broadcast on the PBS series Independent Lens. He is currently writing a book about African diasporic warfare in the Americas.

Elizabeth Maddock Dillon is Professor and Chair of the Department of English and Co-director of the NULab for Texts, Maps, and Networks at Northeastern University. She is the author of _New World Drama: The Performative Commons in the Atlantic World, 1649-1849_ (Duke University Press, 2014) which won the Barnard Hewitt Award for Outstanding Research in Theatre History from the American Society for Theatre Research and _The Gender of Freedom: Fictions of Liberalism and the Literary Public Sphere_ (Stanford University Press, 2004), which won the Heyman Prize for Outstanding Publication in the Humanities at Yale University. She is co-editor with Michael Drexler of "The Haitian Revolution and the Early U.S.: Histories, Geographies, Textualities," which is forthcoming from the University of Pennsylvania Press. Dillon is the co-director of the Futures of American Studies Institute at Dartmouth College and the former the chair of the American Literature Section of the Modern Language Association. She currently serves on the editorial boards of _Signs_ and the _Women Writers Project_ and has served on the editorial boards of _Early American Literature_ and _American Literature_ and the advisory board of _PMLA_. She is the founder of the award-winning crowd-sourced digital archive [Our Marathon: The Boston Bombing Digital Archive](http://marathon.neu.edu/about), and the co-founder and co-director of the [Early Caribbean Digital Archive](http://ecda.northeastern.edu).

Laurent Dubois is Professor of Romance Studies and History and Director of the the Forum for Scholars & Publics at Duke University. He is the author of A Colony of Citizens: Revolution & Slave Emancipation in the French Caribbean, 1787-1804 (2004), Avengers of the New World: The Story of the Haitian Revolution (2004), Soccer Empire: The World Cup and the Future of France (2010), Haiti: The Aftershocks of History (2012) and most recently The Banjo: America’s African Instrument (2016). His writings have appeared in The Nation, The New Yorker, the New York Times, Slate, Sports Illustrated, and The New Republic. In 2016-18 he was a fellow at the National Humanities Center, where he is working on two projects: a book on soccer called The Language of the Game (under contract with Basic Books), and an experimental biography of Katherine Dunham. 

Schuyler Esprit is a scholar of Caribbean literature and cultural studies, and postcolonial theory.  Dr. Esprit holds a PhD in English literature from University of Maryland – College Park. She is the Founding Director of Create Caribbean Inc., Research Institute at Dominica State College. The Research Institute supports students and scholars to use digital technologies for research, teaching and learning in areas of Caribbean development, especially its culture, history and heritage. She currently works as Registrar and Dean of Academic Affairs at Dominica State College. Esprit is a writer and editor, research consultant, and youth advocate. She has also taught and held professional positions at a number of universities in the United States, and has also worked as the Editor of Dominica’s longest running newspaper, The Chronicle. She is now completing her book entitled West Indian Readers: A Social History and its digital companion, both of which are historical explorations of reading culture in the Caribbean. She has also written the introduction to the 2016 Papillote Press edition of The Orchid House, the 1953 novel by Dominican writer Phyllis Shand Allfrey. 

Jessica Marie Johnson is Assistant Professor of History at Michigan State University. Her work has appeared in Slavery & Abolition, The Black Scholar, Meridians: Feminism, Race and Transnationalism, and Debates in the Digital Humanities. As a digital humanist, Johnson explores the way digital and social media disseminate and create historical narratives, in particular, comparative histories of slavery and people of African descent.

Kelly Baker Josephs is Associate Professor of English at York College, CUNY. She is the author of Disturbers of the Peace: Representations of Insanity in Anglophone Caribbean Literature (2013), editor of sx salon: a small axe literary platform, and manager of The Caribbean Commons website. Her current project, “Caribbean Articulations: Storytelling in a Digital Age,” explores the intersections between new technologies and Caribbean cultural production.

Frances Negrón-Muntaner is an award-winning filmmaker, writer, curator, scholar and professor at Columbia University, where she is the founding director of the Media and Idea Lab and founding curator of the Latino Arts and Activism Archive at Columbia’s Rare Books and Manuscripts Library. Among her books and publications are: Boricua Pop: Puerto Ricans and the Latinization of American Culture (CHOICE Award, 2004), The Latino Media Gap (2014), and Sovereign Acts (forthcoming). Her most recent films include Small City, Big Change (2013), War for Guam (2015) and Life Outside (2016). For her work as a scholar and filmmaker, Negrón-Muntaner has received Ford, Truman, Scripps Howard, Rockefeller, Pew, and Chang-Chavkin fellowships. Major funders such as Social Science Research Council, Andy Warhol Foundation, and Independent Television Service have also supported her work. In 2008, the United Nations' Rapid Response Media Mechanism recognized her as a global expert in the areas of mass media and Latin/o American studies; in 2012, she received the Lenfest Award, one of Columbia University's most prestigious recognitions for excellence in teaching and scholarship. Most recently, she was the recipient of a 2017 OZY Educator Award.. Negrón-Muntaner also served as director of Columbia’s Center for the Study of Ethnicity and Race from 2009-2016.

Laurie N. Taylor is the Digital Scholarship Librarian at the University of Florida, and Digital Scholarship Director for the international collaborative Digital Library of the Caribbean (dLOC). Her work focuses on digital scholarship and developing socio-technical supports (people, policies, technologies, communities) for scholarly cyberinfrastructure to foster an environment of radical collaboration that supports diversity and inclusivity. She is the Editor-in-Chief of the LibraryPress@UF, a joint imprint of the UF Libraries and Press, member of the UF Digital Humanities Graduate Certificate Board, affiliate librarian for the Center for Gender, Sexualities, and Women’s Studies Research, and affiliate faculty member in the UF’s Center for Latin American Studies.

**Comment by elotroalex** [comment]
done
